### ISSUE TITLE
Actualización a Delegaciones, Sectores y Colonias

### ISSUE THREAD

**Issue by oxcar** [CodeandoMexico/decidim-monterrey#63]
Ha cambiado la manera en que se estructuran los ámbitos (scopes). 

Ahora en vez de Distritos (9) y Colonias (1122), pasamos a tener Delegaciones (5), Sectores (36) y Colonias (1122?).

Este documento contiene la nueva redistritación:
https://docs.google.com/spreadsheets/d/1w0nM4TUzJ-7he5Yof-RvPSN0hDvPuzIr/edit?usp=sharing&ouid=112270365085174745472&rtpof=true&sd=true

Tareas:

- [x] Crear fichero CSV con las delegaciones
- [x] Crear fichero CSV con los sectores
- [x] Cerar fichero CSV con las colonias
- [x] Actualizar el fichero [seeds.rb](https://github.com/CodeandoMexico/decidim-monterrey/blob/c53b4f81f3073b6c552b1eb6fd989a20d6ea4548/db/seeds.rb) para que cree de manera la estructura de Scopes y Scope Types en la BBDD.
- [x] Actualizar el proceso de solicitud de verificación. Cuando el usuario se quiere verificar lo solicita con su INE y su colonia. Es necesario guardar el ID de la colonia, el ID del sector y el ID de la delegación en el campo metadata del Authorization. Relacionado con #25.
- [x] En la pantalla del Admin de revisión de solicitudes de verificación es necesario mostrar colonia, sector y distrito, en vez de solo colonia y distrito. Relacionado con #25.
- [x] A la hora de crear una propuesta, es necesario leer la configruación del proceso participativo para saber si se trata de un proceso a nivel de sector o a nivel de delegación. Asociar el ID de ámbito (scope) de delegación o sector. Relacionado con #50 
- [x] A la hora de poder votar una propuesta, es necesario leer la configruación del proceso participativo para saber si se trata de un proceso a nivel de sector o a nivel de delegación, permitir o denegar el voto en función del ámbito del objeto authorization del usuario. Un usuario solo puede votar propuestas de su delegación o de su sector. Relacionado con #51

**Comment by oxcar** [comment]
Probado en desarrollo. Una posible mejora es realizar tests automatizados.
